### ISSUE TITLE
Find a solution for the Crtl + D input

### ISSUE THREAD

**Issue by pmeising** [mochan42/ft_IRC#34]
When the Client sends partial data and then ends the communication by providing an EOF command like in the following example:

>>>> /JO CRTL +D
>>>> IN

If the command is continued in a new line after having sent the first (partial) command, the Server should be able to connect the dots and recognize the  command as /JOIN instead of treating it as 2 seperate messages.

**Comment by pmeising** [comment]
Ctrl. + D simply means EOF - end of file and therefore ends the message sent to the Server.

**Comment by Triinuj** [comment]
In testing, most likely solved.
