### ISSUE TITLE
[Server] Implement createUser() function

### ISSUE THREAD

**Issue by pmeising** [mochan42/ft_IRC#45]
Implement createUser() like defined in the Server.hpp file.

**Comment by pmeising** [comment]
Who do you need to do the review? Just assign them to the issue pls. :)

**Comment by mochan42** [comment]
@fsemke please kindly let us know if the createUser and getUser function work. If not, reach out and I will fix it :)

**Comment by mochan42** [comment]
@fsemke to be explicit, this current project issue is related to the 2 PR I submitted : #49  and #50

**Comment by fsemke** [comment]
I don't think the createUser() is for me. Right now i don't know were i need it. I can't test getUser() right now but i will. I let you know

**Comment by fsemke** [comment]
Working
