### ISSUE TITLE
Message from nc doesn't get sent to HexChat user when more than 1 arg

### ISSUE THREAD

**Issue by pmeising** [mochan42/ft_IRC#74]
![Image](https://user-images.githubusercontent.com/96015618/234565695-273b3583-633f-4eb6-86d1-1792618082ae.png)

**Comment by pmeising** [comment]
Probably an iteration issue.

**Comment by Triinuj** [comment]
From hexchat the messages come with ":" sign at the beginning and are parsed as single trailing argument starting from ":", 
In nc there isn´t obligation to add ":" 
I updated sendChannelMessage and sendPrivateMessage functions to concatenate several args into one string before sending.

**Comment by Triinuj** [comment]
![image](https://user-images.githubusercontent.com/81394561/234903658-7e0e5562-267a-4de5-81ec-3cf933f3af0e.png)
