### ISSUE TITLE
/Pass has to be first command

### ISSUE THREAD

**Issue by pmeising** [mochan42/ft_IRC#91]
![Image](https://user-images.githubusercontent.com/96015618/235094102-082e7680-536b-4493-b83b-215818cb70e0.png)

**Comment by pmeising** [comment]
Looks like we need to prohibit the effectuation of /nick and /user if the /pass was not sent before. i.e. if the user is not confirming they have the correct access rights to the server.

**Comment by fsemke** [comment]
/pass needs to be the first now.
